public enum SFXClip
{
    GunShot,
    SilencerShot,
    MachinegunShot,
    ShotgunShot,
    GunReload,
    MachinegunReload,
    ShotgunReload,
    ItemPickup,
    Bandaging,
    BulletHitsCharacter,
    GrenadeThrow,
    Crafting,
    BulletToDoorHit,
    KeyboardTyping,
    BoxSmash,
    PortalSound,
    BushRattle,
    PatchingSound,
    GunLoad,
    MachineGunLoad,
    ShotgunLoad,
    Lockpicking,
    None = 99999
}